cc_library(
    name = "tcp_server",
    srcs = ["tcp_server.cc",
            "tcp_message.cc"],
    hdrs = ["tcp_server.hh",
            "tcp_message.hh"],
    visibility = ["//visibility:public"]
)

