cc_library(
    name = "json",
    srcs = ["json.cc",
            "parser.cc"],
    hdrs = ["json.hh",
            "parser.hh"],
    deps = ["@variant//:variant"],
    visibility = ["//visibility:public"]
)

