cc_test(
    name = "whitespace_test",
    srcs = ["whitespace_test.cc"],
    deps = ["//json:json"]
)

cc_test(
    name = "parsing_tests",
    srcs = ["parsing_tests.cc"],
    deps = ["//json:json"]
)
